/*
 * 城市英文名 → 中文名静态词典(地球仪 GeoIP 专用,只进 worker chunk)。
 *
 * 为什么需要它:DB-IP City Lite 的 mmdb 里 names 只有 en 一种语言,
 * 词典是把城市名本地化成中文的唯一途径(国家名不在此列 ——
 * 国家名走 Intl.DisplayNames,区域名全集内建于 JS 引擎,零词典、全覆盖)。
 *
 * 收录策略:代理面板真正会见到的城市 —— 数据中心/骨干网城市全收,
 * 中国大陆地级市尽量全收(DB-IP 对国内 IP 返回拼音市名),港澳台/日韩/东南亚/
 * 欧美主要城市收常见集。查不到的名字原样显示英文,这是刻意的兜底:
 * 一个错误的中文名比英文名更糟。
 *
 * 键必须与 mmdb 的 en 名逐字节相等(含变音符/撇号),拿不准的拼法两种都收
 * (如 Xi'an / Xi’an、São Paulo / Sao Paulo)。
 * 简繁:词典只有简体;zh-TW 用户看到简体城市名 + 繁体国家名(Intl 出的),
 * 这是「有中文但混简繁」与「一半英文」之间的取舍,选前者。
 * 同拼音歧义(泰州/台州、玉林/榆林、福州/抚州)取 IP 数据里更常见的一个。
 */

export const CITY_ZH: Record<string, string> = {
  // ─── 中国大陆:直辖市/省会/主要城市 ───
  Beijing: '北京',
  Shanghai: '上海',
  Tianjin: '天津',
  Chongqing: '重庆',
  Guangzhou: '广州',
  Shenzhen: '深圳',
  Chengdu: '成都',
  Hangzhou: '杭州',
  Wuhan: '武汉',
  "Xi'an": '西安',
  'Xi’an': '西安',
  Xian: '西安',
  Nanjing: '南京',
  Suzhou: '苏州',
  Changsha: '长沙',
  Zhengzhou: '郑州',
  Qingdao: '青岛',
  Jinan: '济南',
  Shenyang: '沈阳',
  Dalian: '大连',
  Harbin: '哈尔滨',
  Changchun: '长春',
  Kunming: '昆明',
  Guiyang: '贵阳',
  Nanning: '南宁',
  Fuzhou: '福州',
  Xiamen: '厦门',
  Ningbo: '宁波',
  Wenzhou: '温州',
  Hefei: '合肥',
  Nanchang: '南昌',
  Taiyuan: '太原',
  Shijiazhuang: '石家庄',
  Lanzhou: '兰州',
  Xining: '西宁',
  Yinchuan: '银川',
  Urumqi: '乌鲁木齐',
  Ürümqi: '乌鲁木齐',
  Lhasa: '拉萨',
  Hohhot: '呼和浩特',
  Haikou: '海口',
  Sanya: '三亚',

  // ─── 中国大陆:地级市 ───
  Zhuhai: '珠海',
  Foshan: '佛山',
  Dongguan: '东莞',
  Zhongshan: '中山',
  Huizhou: '惠州',
  Jiangmen: '江门',
  Shantou: '汕头',
  Chaozhou: '潮州',
  Jieyang: '揭阳',
  Zhanjiang: '湛江',
  Maoming: '茂名',
  Yangjiang: '阳江',
  Qingyuan: '清远',
  Shaoguan: '韶关',
  Meizhou: '梅州',
  Shanwei: '汕尾',
  Heyuan: '河源',
  Zhaoqing: '肇庆',
  Yunfu: '云浮',
  Wuxi: '无锡',
  Changzhou: '常州',
  Nantong: '南通',
  Xuzhou: '徐州',
  Yangzhou: '扬州',
  Zhenjiang: '镇江',
  Taizhou: '台州',
  Yancheng: '盐城',
  "Huai'an": '淮安',
  'Huai’an': '淮安',
  Lianyungang: '连云港',
  Suqian: '宿迁',
  Shaoxing: '绍兴',
  Jiaxing: '嘉兴',
  Huzhou: '湖州',
  Jinhua: '金华',
  Quzhou: '衢州',
  Zhoushan: '舟山',
  Lishui: '丽水',
  Weifang: '潍坊',
  Yantai: '烟台',
  Weihai: '威海',
  Zibo: '淄博',
  Linyi: '临沂',
  Jining: '济宁',
  Dezhou: '德州',
  Liaocheng: '聊城',
  Binzhou: '滨州',
  Dongying: '东营',
  "Tai'an": '泰安',
  'Tai’an': '泰安',
  Rizhao: '日照',
  Heze: '菏泽',
  Zaozhuang: '枣庄',
  Luoyang: '洛阳',
  Kaifeng: '开封',
  Anyang: '安阳',
  Xinxiang: '新乡',
  Nanyang: '南阳',
  Xuchang: '许昌',
  Zhoukou: '周口',
  Shangqiu: '商丘',
  Xinyang: '信阳',
  Zhumadian: '驻马店',
  Pingdingshan: '平顶山',
  Jiaozuo: '焦作',
  Puyang: '濮阳',
  Luohe: '漯河',
  Sanmenxia: '三门峡',
  Hebi: '鹤壁',
  Xiangyang: '襄阳',
  Yichang: '宜昌',
  Jingzhou: '荆州',
  Huangshi: '黄石',
  Shiyan: '十堰',
  Xiaogan: '孝感',
  Huanggang: '黄冈',
  Xianning: '咸宁',
  Ezhou: '鄂州',
  Jingmen: '荆门',
  Suizhou: '随州',
  Zhuzhou: '株洲',
  Xiangtan: '湘潭',
  Hengyang: '衡阳',
  Yueyang: '岳阳',
  Changde: '常德',
  Chenzhou: '郴州',
  Yiyang: '益阳',
  Loudi: '娄底',
  Shaoyang: '邵阳',
  Huaihua: '怀化',
  Yongzhou: '永州',
  Zhangjiajie: '张家界',
  Guilin: '桂林',
  Liuzhou: '柳州',
  Beihai: '北海',
  Qinzhou: '钦州',
  Yulin: '玉林',
  Guigang: '贵港',
  Wuzhou: '梧州',
  Baise: '百色',
  Hechi: '河池',
  Laibin: '来宾',
  Fangchenggang: '防城港',
  Chongzuo: '崇左',
  Hezhou: '贺州',
  Baotou: '包头',
  Ordos: '鄂尔多斯',
  Chifeng: '赤峰',
  Tongliao: '通辽',
  Hulunbuir: '呼伦贝尔',
  Bayannur: '巴彦淖尔',
  Wuhai: '乌海',
  Datong: '大同',
  Yuncheng: '运城',
  Linfen: '临汾',
  Changzhi: '长治',
  Jincheng: '晋城',
  Jinzhong: '晋中',
  Shuozhou: '朔州',
  Xinzhou: '忻州',
  Lvliang: '吕梁',
  Xianyang: '咸阳',
  Baoji: '宝鸡',
  Weinan: '渭南',
  Hanzhong: '汉中',
  Ankang: '安康',
  Shangluo: '商洛',
  Tongchuan: '铜川',
  Tangshan: '唐山',
  Baoding: '保定',
  Langfang: '廊坊',
  Cangzhou: '沧州',
  Handan: '邯郸',
  Xingtai: '邢台',
  Qinhuangdao: '秦皇岛',
  Zhangjiakou: '张家口',
  Chengde: '承德',
  Hengshui: '衡水',
  Anshan: '鞍山',
  Fushun: '抚顺',
  Benxi: '本溪',
  Jinzhou: '锦州',
  Yingkou: '营口',
  Panjin: '盘锦',
  Dandong: '丹东',
  Liaoyang: '辽阳',
  Fuxin: '阜新',
  Huludao: '葫芦岛',
  Tieling: '铁岭',
  Jilin: '吉林',
  Siping: '四平',
  Tonghua: '通化',
  Baishan: '白山',
  Songyuan: '松原',
  Baicheng: '白城',
  Yanji: '延吉',
  Qiqihar: '齐齐哈尔',
  Mudanjiang: '牡丹江',
  Jiamusi: '佳木斯',
  Daqing: '大庆',
  Suihua: '绥化',
  Heihe: '黑河',
  Hegang: '鹤岗',
  Shuangyashan: '双鸭山',
  Qitaihe: '七台河',
  Jixi: '鸡西',
  Mianyang: '绵阳',
  Deyang: '德阳',
  Leshan: '乐山',
  Yibin: '宜宾',
  Luzhou: '泸州',
  Nanchong: '南充',
  Dazhou: '达州',
  Zigong: '自贡',
  Panzhihua: '攀枝花',
  Suining: '遂宁',
  Neijiang: '内江',
  "Guang'an": '广安',
  'Guang’an': '广安',
  "Ya'an": '雅安',
  'Ya’an': '雅安',
  Bazhong: '巴中',
  Ziyang: '资阳',
  Meishan: '眉山',
  Guangyuan: '广元',
  Zunyi: '遵义',
  Liupanshui: '六盘水',
  Anshun: '安顺',
  Bijie: '毕节',
  Tongren: '铜仁',
  Qujing: '曲靖',
  Yuxi: '玉溪',
  Zhaotong: '昭通',
  Lijiang: '丽江',
  Dali: '大理',
  Ganzhou: '赣州',
  Jiujiang: '九江',
  Shangrao: '上饶',
  Yichun: '宜春',
  "Ji'an": '吉安',
  'Ji’an': '吉安',
  Pingxiang: '萍乡',
  Jingdezhen: '景德镇',
  Xinyu: '新余',
  Yingtan: '鹰潭',
  Quanzhou: '泉州',
  Zhangzhou: '漳州',
  Putian: '莆田',
  Nanping: '南平',
  Sanming: '三明',
  Longyan: '龙岩',
  Ningde: '宁德',
  Wuhu: '芜湖',
  Bengbu: '蚌埠',
  Huainan: '淮南',
  "Ma'anshan": '马鞍山',
  'Ma’anshan': '马鞍山',
  Huaibei: '淮北',
  Tongling: '铜陵',
  Anqing: '安庆',
  Huangshan: '黄山',
  Chuzhou: '滁州',
  Fuyang: '阜阳',
  "Lu'an": '六安',
  'Lu’an': '六安',
  Bozhou: '亳州',
  Chizhou: '池州',
  Xuancheng: '宣城',

  // ─── 北京/上海常见区名(DB-IP 对部分国内 IP 落到区一级) ───
  Haidian: '海淀',
  Xicheng: '西城',
  Dongcheng: '东城',
  Fengtai: '丰台',
  Shijingshan: '石景山',
  Tongzhou: '通州',
  Daxing: '大兴',
  Shunyi: '顺义',
  Changping: '昌平',
  Pudong: '浦东',
  Minhang: '闵行',
  Xuhui: '徐汇',
  Putuo: '普陀',
  Baoshan: '宝山',
  Jiading: '嘉定',
  Songjiang: '松江',
  Qingpu: '青浦',
  Fengxian: '奉贤',
  Shizishan: '狮子山',
  Jinshan: '金山',

  // ─── 港澳台 ───
  'Hong Kong': '香港',
  Kowloon: '九龙',
  'Tsuen Wan': '荃湾',
  'Sha Tin': '沙田',
  'Yuen Long': '元朗',
  Macau: '澳门',
  Macao: '澳门',
  Taipei: '台北',
  'New Taipei': '新北',
  'New Taipei City': '新北',
  Taichung: '台中',
  Kaohsiung: '高雄',
  Tainan: '台南',
  Taoyuan: '桃园',
  Hsinchu: '新竹',
  Keelung: '基隆',
  Chiayi: '嘉义',
  Changhua: '彰化',
  Pingtung: '屏东',
  Yilan: '宜兰',
  Hualien: '花莲',
  Taitung: '台东',
  Nantou: '南投',
  Miaoli: '苗栗',
  Douliu: '斗六',
  Banqiao: '板桥',
  Zhongli: '中坜',

  // ─── 日本 ───
  Tokyo: '东京',
  Osaka: '大阪',
  Nagoya: '名古屋',
  Yokohama: '横滨',
  Fukuoka: '福冈',
  Sapporo: '札幌',
  Kyoto: '京都',
  Kobe: '神户',
  Kawasaki: '川崎',
  Saitama: '埼玉',
  Chiba: '千叶',
  Sendai: '仙台',
  Hiroshima: '广岛',
  Naha: '那霸',
  Sakai: '堺',
  Niigata: '新潟',
  Hamamatsu: '滨松',
  Okayama: '冈山',
  Kumamoto: '熊本',
  Shizuoka: '静冈',
  Kagoshima: '鹿儿岛',
  Kanazawa: '金泽',
  Utsunomiya: '宇都宫',
  Matsuyama: '松山',
  Nagasaki: '长崎',
  Oita: '大分',
  Gifu: '岐阜',
  Toyama: '富山',
  Takamatsu: '高松',
  Akita: '秋田',
  Aomori: '青森',
  Morioka: '盛冈',
  Fukushima: '福岛',
  Yamagata: '山形',
  Nagano: '长野',
  Mito: '水户',
  Kofu: '甲府',
  Nara: '奈良',
  Otsu: '大津',
  Wakayama: '和歌山',
  Tottori: '鸟取',
  Matsue: '松江',
  Yamaguchi: '山口',
  Tokushima: '德岛',
  Saga: '佐贺',
  Miyazaki: '宫崎',
  Fukui: '福井',
  Tsu: '津',
  Maebashi: '前桥',
  Inzai: '印西',
  Funabashi: '船桥',
  Ichikawa: '市川',
  Urayasu: '浦安',
  Koto: '江东',
  Shinjuku: '新宿',
  Shibuya: '涩谷',
  Minato: '港区',
  Chiyoda: '千代田',
  Suginami: '杉并',
  Setagaya: '世田谷',
  Ota: '大田',
  Nerima: '练马',
  Adachi: '足立',
  Chuo: '中央区',
  Osaki: '大崎',
  Toshima: '丰岛',
  Bunkyo: '文京',
  Taito: '台东',
  Sumida: '墨田',
  Katsushika: '葛饰',
  Edogawa: '江户川',
  Itabashi: '板桥',
  Kita: '北区',
  Arakawa: '荒川',
  Meguro: '目黑',
  Shinagawa: '品川',
  Nakano: '中野',
  Heiwajima: '平和岛',

  // ─── 韩国 ───
  Seoul: '首尔',
  Busan: '釜山',
  Incheon: '仁川',
  Daegu: '大邱',
  Daejeon: '大田',
  Gwangju: '光州',
  Ulsan: '蔚山',
  Suwon: '水原',
  Seongnam: '城南',
  Goyang: '高阳',
  Yongin: '龙仁',
  Bucheon: '富川',
  Ansan: '安山',
  Cheongju: '清州',
  Jeonju: '全州',
  Cheonan: '天安',
  Pohang: '浦项',
  Changwon: '昌原',
  Gimhae: '金海',
  Jeju: '济州',
  Chuncheon: '春川',
  'Gangnam-gu': '江南区',
  'Seocho-gu': '瑞草区',
  'Guro-gu': '九老区',
  'Geumcheon-gu': '衿川区',
  'Yongsan-gu': '龙山区',
  'Yongsan-dong': '龙山洞',
  'Mapo-gu': '麻浦区',
  'Songpa-gu': '松坡区',
  'Yeongdeungpo-gu': '永登浦区',
  'Jung-gu': '中区',
  'Jongno-gu': '钟路区',
  'Bundang-gu': '盆唐区',
  'Dongjak-gu': '铜雀区',
  'Gwangjin-gu': '广津区',
  'Seongdong-gu': '城东区',
  Pyongyang: '平壤',

  // ─── 东南亚 / 南亚 / 中亚 ───
  Singapore: '新加坡',
  Bangkok: '曼谷',
  'Chiang Mai': '清迈',
  Pattaya: '芭提雅',
  Phuket: '普吉',
  'Kuala Lumpur': '吉隆坡',
  'Johor Bahru': '新山',
  Penang: '槟城',
  'George Town': '乔治市',
  Cyberjaya: '赛城',
  Jakarta: '雅加达',
  Surabaya: '泗水',
  Bandung: '万隆',
  Medan: '棉兰',
  Denpasar: '登巴萨',
  Manila: '马尼拉',
  'Quezon City': '奎松城',
  Makati: '马卡蒂',
  Cebu: '宿务',
  'Cebu City': '宿务',
  Davao: '达沃',
  Hanoi: '河内',
  'Ho Chi Minh City': '胡志明市',
  'Da Nang': '岘港',
  Haiphong: '海防',
  'Can Tho': '芹苴',
  'Phnom Penh': '金边',
  'Siem Reap': '暹粒',
  Sihanoukville: '西哈努克市',
  Vientiane: '万象',
  Yangon: '仰光',
  Naypyidaw: '内比都',
  Mandalay: '曼德勒',
  'Bandar Seri Begawan': '斯里巴加湾市',
  Dili: '帝力',
  Mumbai: '孟买',
  'New Delhi': '新德里',
  Delhi: '德里',
  Bangalore: '班加罗尔',
  Bengaluru: '班加罗尔',
  Chennai: '金奈',
  Hyderabad: '海得拉巴',
  Kolkata: '加尔各答',
  Pune: '浦那',
  Ahmedabad: '艾哈迈达巴德',
  Jaipur: '斋浦尔',
  Noida: '诺伊达',
  Gurgaon: '古尔冈',
  Lucknow: '勒克瑙',
  Karachi: '卡拉奇',
  Lahore: '拉合尔',
  Islamabad: '伊斯兰堡',
  Rawalpindi: '拉瓦尔品第',
  Faisalabad: '费萨拉巴德',
  Dhaka: '达卡',
  Chittagong: '吉大港',
  Colombo: '科伦坡',
  Kathmandu: '加德满都',
  Thimphu: '廷布',
  Male: '马累',
  Malé: '马累',
  Kabul: '喀布尔',
  Ulaanbaatar: '乌兰巴托',
  Almaty: '阿拉木图',
  Astana: '阿斯塔纳',
  'Nur-Sultan': '阿斯塔纳',
  Tashkent: '塔什干',
  Samarkand: '撒马尔罕',
  Bishkek: '比什凯克',
  Dushanbe: '杜尚别',
  Ashgabat: '阿什哈巴德',
  Baku: '巴库',
  Tbilisi: '第比利斯',
  Yerevan: '埃里温',

  // ─── 中东 ───
  Dubai: '迪拜',
  'Abu Dhabi': '阿布扎比',
  Sharjah: '沙迦',
  Doha: '多哈',
  Riyadh: '利雅得',
  Jeddah: '吉达',
  Dammam: '达曼',
  Mecca: '麦加',
  Medina: '麦地那',
  'Kuwait City': '科威特城',
  Manama: '麦纳麦',
  Muscat: '马斯喀特',
  'Tel Aviv': '特拉维夫',
  Jerusalem: '耶路撒冷',
  Haifa: '海法',
  Amman: '安曼',
  Beirut: '贝鲁特',
  Damascus: '大马士革',
  Baghdad: '巴格达',
  Basra: '巴士拉',
  Erbil: '埃尔比勒',
  Tehran: '德黑兰',
  Mashhad: '马什哈德',
  Isfahan: '伊斯法罕',
  Sanaa: '萨那',

  // ─── 北美:美国 ───
  'New York': '纽约',
  'New York City': '纽约',
  Brooklyn: '布鲁克林',
  Queens: '皇后区',
  Manhattan: '曼哈顿',
  Bronx: '布朗克斯',
  'Staten Island': '斯塔滕岛',
  Buffalo: '布法罗',
  Albany: '奥尔巴尼',
  Rochester: '罗切斯特',
  Syracuse: '锡拉丘兹',
  'Los Angeles': '洛杉矶',
  'San Francisco': '旧金山',
  'San Jose': '圣何塞',
  'Santa Clara': '圣克拉拉',
  Sunnyvale: '森尼韦尔',
  'Mountain View': '山景城',
  'Palo Alto': '帕洛阿尔托',
  Cupertino: '库比蒂诺',
  'Menlo Park': '门洛帕克',
  Fremont: '弗里蒙特',
  Oakland: '奥克兰',
  Berkeley: '伯克利',
  Sacramento: '萨克拉门托',
  'San Diego': '圣迭戈',
  Irvine: '尔湾',
  Anaheim: '阿纳海姆',
  'Long Beach': '长滩',
  Riverside: '里弗赛德',
  Bakersfield: '贝克斯菲尔德',
  'San Bernardino': '圣贝纳迪诺',
  'Santa Monica': '圣莫尼卡',
  Pasadena: '帕萨迪纳',
  Burbank: '伯班克',
  Glendale: '格伦代尔',
  'Las Vegas': '拉斯维加斯',
  Reno: '里诺',
  Phoenix: '凤凰城',
  Tucson: '图森',
  Mesa: '梅萨',
  Chandler: '钱德勒',
  Scottsdale: '斯科茨代尔',
  Tempe: '坦佩',
  Seattle: '西雅图',
  Tacoma: '塔科马',
  Spokane: '斯波坎',
  Redmond: '雷德蒙德',
  Bellevue: '贝尔维尤',
  Quincy: '昆西',
  Portland: '波特兰',
  Hillsboro: '希尔斯伯勒',
  Boardman: '博德曼',
  'The Dalles': '达尔斯',
  Prineville: '普林维尔',
  Eugene: '尤金',
  Salem: '塞勒姆',
  Boise: '博伊西',
  'Salt Lake City': '盐湖城',
  Provo: '普罗沃',
  Ogden: '奥格登',
  Denver: '丹佛',
  'Colorado Springs': '科罗拉多斯普林斯',
  Aurora: '奥罗拉',
  Cheyenne: '夏延',
  Albuquerque: '阿尔伯克基',
  'El Paso': '埃尔帕索',
  Dallas: '达拉斯',
  'Fort Worth': '沃思堡',
  Houston: '休斯敦',
  'San Antonio': '圣安东尼奥',
  Austin: '奥斯汀',
  Plano: '普莱诺',
  Garland: '加兰',
  Richardson: '理查森',
  'Oklahoma City': '俄克拉何马城',
  Tulsa: '塔尔萨',
  'Kansas City': '堪萨斯城',
  Wichita: '威奇托',
  Omaha: '奥马哈',
  Lincoln: '林肯',
  'Council Bluffs': '康瑟尔布拉夫斯',
  'Des Moines': '得梅因',
  Minneapolis: '明尼阿波利斯',
  'Saint Paul': '圣保罗',
  Chicago: '芝加哥',
  'Elk Grove Village': '埃尔克格罗夫村',
  Naperville: '内珀维尔',
  Milwaukee: '密尔沃基',
  Madison: '麦迪逊',
  Detroit: '底特律',
  'Ann Arbor': '安阿伯',
  'Grand Rapids': '大急流城',
  Lansing: '兰辛',
  Indianapolis: '印第安纳波利斯',
  Columbus: '哥伦布',
  Cleveland: '克利夫兰',
  Cincinnati: '辛辛那提',
  Dayton: '代顿',
  Toledo: '托莱多',
  Akron: '阿克伦',
  'New Albany': '新奥尔巴尼',
  'Saint Louis': '圣路易斯',
  'St. Louis': '圣路易斯',
  Nashville: '纳什维尔',
  Memphis: '孟菲斯',
  Knoxville: '诺克斯维尔',
  Chattanooga: '查塔努加',
  Louisville: '路易维尔',
  Lexington: '列克星敦',
  Atlanta: '亚特兰大',
  Savannah: '萨凡纳',
  Charlotte: '夏洛特',
  Raleigh: '罗利',
  Durham: '达勒姆',
  Greensboro: '格林斯伯勒',
  'Winston-Salem': '温斯顿-塞勒姆',
  Charleston: '查尔斯顿',
  Columbia: '哥伦比亚',
  Jacksonville: '杰克逊维尔',
  Miami: '迈阿密',
  Orlando: '奥兰多',
  Tampa: '坦帕',
  'St. Petersburg': '圣彼得斯堡',
  'Fort Lauderdale': '劳德代尔堡',
  Gainesville: '盖恩斯维尔',
  Tallahassee: '塔拉哈西',
  'New Orleans': '新奥尔良',
  'Baton Rouge': '巴吞鲁日',
  Birmingham: '伯明翰',
  Montgomery: '蒙哥马利',
  Huntsville: '亨茨维尔',
  Jackson: '杰克逊',
  'Little Rock': '小石城',
  Washington: '华盛顿',
  Arlington: '阿灵顿',
  Alexandria: '亚历山德里亚',
  Ashburn: '阿什本',
  Reston: '雷斯顿',
  Sterling: '斯特灵',
  Herndon: '赫恩登',
  Chantilly: '尚蒂伊',
  Manassas: '马纳萨斯',
  Leesburg: '利斯堡',
  Culpeper: '卡尔佩珀',
  Richmond: '里士满',
  'Virginia Beach': '弗吉尼亚比奇',
  Norfolk: '诺福克',
  Baltimore: '巴尔的摩',
  Philadelphia: '费城',
  Pittsburgh: '匹兹堡',
  Harrisburg: '哈里斯堡',
  Allentown: '阿伦敦',
  Newark: '纽瓦克',
  'Jersey City': '泽西城',
  Piscataway: '皮斯卡特维',
  Secaucus: '锡考克斯',
  Edison: '爱迪生',
  Trenton: '特伦顿',
  Weehawken: '威霍肯',
  Boston: '波士顿',
  Cambridge: '剑桥',
  Worcester: '伍斯特',
  Providence: '普罗维登斯',
  Hartford: '哈特福德',
  'New Haven': '纽黑文',
  Stamford: '斯坦福德',
  Manchester: '曼彻斯特',
  Portsmouth: '朴次茅斯',
  Burlington: '伯灵顿',
  Honolulu: '檀香山',
  Anchorage: '安克雷奇',

  // ─── 北美:加拿大 / 墨西哥 ───
  Toronto: '多伦多',
  Montreal: '蒙特利尔',
  Montréal: '蒙特利尔',
  Vancouver: '温哥华',
  Calgary: '卡尔加里',
  Edmonton: '埃德蒙顿',
  Ottawa: '渥太华',
  Winnipeg: '温尼伯',
  'Quebec City': '魁北克城',
  Halifax: '哈利法克斯',
  Victoria: '维多利亚',
  Saskatoon: '萨斯卡通',
  Regina: '里贾纳',
  Mississauga: '密西沙加',
  Markham: '万锦',
  Beauharnois: '博阿尔努瓦',
  'Mexico City': '墨西哥城',
  Guadalajara: '瓜达拉哈拉',
  Monterrey: '蒙特雷',
  Querétaro: '克雷塔罗',
  Queretaro: '克雷塔罗',
  Tijuana: '蒂华纳',
  Cancún: '坎昆',
  Cancun: '坎昆',

  // ─── 欧洲 ───
  London: '伦敦',
  Slough: '斯劳',
  Leeds: '利兹',
  Liverpool: '利物浦',
  Sheffield: '谢菲尔德',
  Bristol: '布里斯托尔',
  Newcastle: '纽卡斯尔',
  Nottingham: '诺丁汉',
  Coventry: '考文垂',
  Cardiff: '加的夫',
  Edinburgh: '爱丁堡',
  Glasgow: '格拉斯哥',
  Belfast: '贝尔法斯特',
  Dublin: '都柏林',
  Cork: '科克',
  Paris: '巴黎',
  Marseille: '马赛',
  Lyon: '里昂',
  Toulouse: '图卢兹',
  Nice: '尼斯',
  Nantes: '南特',
  Strasbourg: '斯特拉斯堡',
  Bordeaux: '波尔多',
  Lille: '里尔',
  Roubaix: '鲁贝',
  Gravelines: '格拉沃利讷',
  'Vitry-sur-Seine': '塞纳河畔维特里',
  'Frankfurt am Main': '法兰克福',
  Frankfurt: '法兰克福',
  Munich: '慕尼黑',
  Berlin: '柏林',
  Hamburg: '汉堡',
  Cologne: '科隆',
  Düsseldorf: '杜塞尔多夫',
  Dusseldorf: '杜塞尔多夫',
  Stuttgart: '斯图加特',
  Nuremberg: '纽伦堡',
  Falkenstein: '法尔肯施泰因',
  Leipzig: '莱比锡',
  Dresden: '德累斯顿',
  Hanover: '汉诺威',
  Bremen: '不来梅',
  Essen: '埃森',
  Dortmund: '多特蒙德',
  Karlsruhe: '卡尔斯鲁厄',
  Mannheim: '曼海姆',
  Amsterdam: '阿姆斯特丹',
  Rotterdam: '鹿特丹',
  'The Hague': '海牙',
  Utrecht: '乌得勒支',
  Eindhoven: '埃因霍温',
  Naaldwijk: '纳尔德韦克',
  Eemshaven: '埃姆斯哈文',
  Groningen: '格罗宁根',
  Brussels: '布鲁塞尔',
  Antwerp: '安特卫普',
  Ghent: '根特',
  'Saint-Ghislain': '圣吉斯兰',
  Luxembourg: '卢森堡',
  Zurich: '苏黎世',
  Zürich: '苏黎世',
  Geneva: '日内瓦',
  Basel: '巴塞尔',
  Bern: '伯尔尼',
  Lausanne: '洛桑',
  Vienna: '维也纳',
  Graz: '格拉茨',
  Linz: '林茨',
  Salzburg: '萨尔茨堡',
  Prague: '布拉格',
  Brno: '布尔诺',
  Ostrava: '俄斯特拉发',
  Warsaw: '华沙',
  Krakow: '克拉科夫',
  Kraków: '克拉科夫',
  Wroclaw: '弗罗茨瓦夫',
  Wrocław: '弗罗茨瓦夫',
  Poznan: '波兹南',
  Poznań: '波兹南',
  Gdansk: '格但斯克',
  Gdańsk: '格但斯克',
  Lodz: '罗兹',
  Łódź: '罗兹',
  Budapest: '布达佩斯',
  Debrecen: '德布勒森',
  Bucharest: '布加勒斯特',
  'Cluj-Napoca': '克卢日-纳波卡',
  Timisoara: '蒂米什瓦拉',
  Timișoara: '蒂米什瓦拉',
  Iasi: '雅西',
  Iași: '雅西',
  Sofia: '索菲亚',
  Plovdiv: '普罗夫迪夫',
  Varna: '瓦尔纳',
  Athens: '雅典',
  Thessaloniki: '塞萨洛尼基',
  Rome: '罗马',
  Milan: '米兰',
  Turin: '都灵',
  Naples: '那不勒斯',
  Florence: '佛罗伦萨',
  Bologna: '博洛尼亚',
  Venice: '威尼斯',
  Palermo: '巴勒莫',
  Genoa: '热那亚',
  Madrid: '马德里',
  Barcelona: '巴塞罗那',
  Valencia: '巴伦西亚',
  Seville: '塞维利亚',
  Zaragoza: '萨拉戈萨',
  Málaga: '马拉加',
  Malaga: '马拉加',
  Bilbao: '毕尔巴鄂',
  Lisbon: '里斯本',
  Porto: '波尔图',
  Stockholm: '斯德哥尔摩',
  Gothenburg: '哥德堡',
  Malmö: '马尔默',
  Malmo: '马尔默',
  Oslo: '奥斯陆',
  Bergen: '卑尔根',
  Copenhagen: '哥本哈根',
  Aarhus: '奥胡斯',
  Odense: '欧登塞',
  Helsinki: '赫尔辛基',
  Espoo: '埃斯波',
  Tampere: '坦佩雷',
  Hamina: '哈米纳',
  Tallinn: '塔林',
  Tartu: '塔尔图',
  Riga: '里加',
  Vilnius: '维尔纽斯',
  Kaunas: '考纳斯',
  Kyiv: '基辅',
  Kiev: '基辅',
  Kharkiv: '哈尔科夫',
  Odesa: '敖德萨',
  Odessa: '敖德萨',
  Dnipro: '第聂伯罗',
  Lviv: '利沃夫',
  Minsk: '明斯克',
  Moscow: '莫斯科',
  'Saint Petersburg': '圣彼得堡',
  'St Petersburg': '圣彼得堡',
  Novosibirsk: '新西伯利亚',
  Yekaterinburg: '叶卡捷琳堡',
  Kazan: '喀山',
  'Nizhny Novgorod': '下诺夫哥罗德',
  Samara: '萨马拉',
  Omsk: '鄂木斯克',
  'Rostov-on-Don': '顿河畔罗斯托夫',
  Krasnoyarsk: '克拉斯诺亚尔斯克',
  Irkutsk: '伊尔库茨克',
  Khabarovsk: '哈巴罗夫斯克',
  Vladivostok: '符拉迪沃斯托克',
  Istanbul: '伊斯坦布尔',
  Ankara: '安卡拉',
  Izmir: '伊兹密尔',
  İzmir: '伊兹密尔',
  Bursa: '布尔萨',
  Antalya: '安塔利亚',
  Belgrade: '贝尔格莱德',
  'Novi Sad': '诺维萨德',
  Zagreb: '萨格勒布',
  Split: '斯普利特',
  Sarajevo: '萨拉热窝',
  Skopje: '斯科普里',
  Podgorica: '波德戈里察',
  Tirana: '地拉那',
  Pristina: '普里什蒂纳',
  Bratislava: '布拉迪斯拉发',
  Ljubljana: '卢布尔雅那',
  Chisinau: '基希讷乌',
  Chișinău: '基希讷乌',
  Reykjavik: '雷克雅未克',
  Reykjavík: '雷克雅未克',
  Nicosia: '尼科西亚',
  Limassol: '利马索尔',
  Valletta: '瓦莱塔',
  Monaco: '摩纳哥',
  Andorra: '安道尔',
  'Andorra la Vella': '安道尔城',
  Gibraltar: '直布罗陀',

  // ─── 大洋洲 ───
  Sydney: '悉尼',
  Melbourne: '墨尔本',
  Brisbane: '布里斯班',
  'South Brisbane': '南布里斯班',
  Perth: '珀斯',
  Adelaide: '阿德莱德',
  Canberra: '堪培拉',
  'Gold Coast': '黄金海岸',
  Hobart: '霍巴特',
  Darwin: '达尔文',
  Auckland: '奥克兰',
  Wellington: '惠灵顿',
  Christchurch: '克赖斯特彻奇',
  Hamilton: '哈密尔顿',
  Suva: '苏瓦',
  'Port Moresby': '莫尔兹比港',
  Nouméa: '努美阿',
  Noumea: '努美阿',

  // ─── 非洲 ───
  Cairo: '开罗',
  Giza: '吉萨',
  Johannesburg: '约翰内斯堡',
  'Cape Town': '开普敦',
  Durban: '德班',
  Pretoria: '比勒陀利亚',
  Lagos: '拉各斯',
  Abuja: '阿布贾',
  Nairobi: '内罗毕',
  Mombasa: '蒙巴萨',
  Casablanca: '卡萨布兰卡',
  Rabat: '拉巴特',
  Marrakesh: '马拉喀什',
  Tunis: '突尼斯',
  Algiers: '阿尔及尔',
  Tripoli: '的黎波里',
  'Addis Ababa': '亚的斯亚贝巴',
  Accra: '阿克拉',
  Abidjan: '阿比让',
  Dakar: '达喀尔',
  Kinshasa: '金沙萨',
  Luanda: '罗安达',
  'Dar es Salaam': '达累斯萨拉姆',
  Kampala: '坎帕拉',
  Kigali: '基加利',
  Lusaka: '卢萨卡',
  Harare: '哈拉雷',
  Maputo: '马普托',
  Antananarivo: '塔那那利佛',
  'Port Louis': '路易港',
  Khartoum: '喀土穆',

  // ─── 拉丁美洲 ───
  'São Paulo': '圣保罗',
  'Sao Paulo': '圣保罗',
  'Rio de Janeiro': '里约热内卢',
  Brasília: '巴西利亚',
  Brasilia: '巴西利亚',
  Fortaleza: '福塔莱萨',
  Salvador: '萨尔瓦多',
  'Belo Horizonte': '贝洛奥里藏特',
  Recife: '累西腓',
  'Porto Alegre': '阿雷格里港',
  Curitiba: '库里蒂巴',
  Campinas: '坎皮纳斯',
  Manaus: '马瑙斯',
  'Buenos Aires': '布宜诺斯艾利斯',
  Córdoba: '科尔多瓦',
  Cordoba: '科尔多瓦',
  Rosario: '罗萨里奥',
  Mendoza: '门多萨',
  Santiago: '圣地亚哥',
  Valparaíso: '瓦尔帕莱索',
  Valparaiso: '瓦尔帕莱索',
  Lima: '利马',
  Arequipa: '阿雷基帕',
  Bogotá: '波哥大',
  Bogota: '波哥大',
  Medellín: '麦德林',
  Medellin: '麦德林',
  Cali: '卡利',
  Quito: '基多',
  Guayaquil: '瓜亚基尔',
  Caracas: '加拉加斯',
  Montevideo: '蒙得维的亚',
  Asunción: '亚松森',
  Asuncion: '亚松森',
  'La Paz': '拉巴斯',
  'Santa Cruz': '圣克鲁斯',
  'Panama City': '巴拿马城',
  'San José': '圣何塞',
  Havana: '哈瓦那',
  'Santo Domingo': '圣多明各',
  'San Juan': '圣胡安',
  Kingston: '金斯敦',
  'Guatemala City': '危地马拉城',
  Tegucigalpa: '特古西加尔巴',
  Managua: '马那瓜',
  'San Salvador': '圣萨尔瓦多',
  Belmopan: '贝尔莫潘',
  Georgetown: '乔治敦',
  Paramaribo: '帕拉马里博',
}
